config/routes.rb
Photosgame::Application.routes.draw do
  


  resources :albums  do
    resources :images
  end
  
  devise_for :users

  match "/:token" => "photos#index"
  

  root :to => 'welcome#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :desc
  
  after_create :generate_token
  
  has_many :images
  
  #唯一url
  def url
    "http://localhost:3000/#{self.token}"
  end
  
  #生成唯一的token
  def generate_token
    begin
      self.token = Album.random
      self.save!
    rescue ActiveRecord::RecordNotUnique => e
      retry
    end
  end
  
  ID_LENGTH = 128
  class << self
    def random(bitlength = ID_LENGTH)
      limit = 2 ** bitlength - 1
      max_size = limit.to_s(36).size
      string = rand(limit).to_s(36)
      string = '0' + string while string.size < max_size
      string
    end
  end
  
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :file, :order
  
  mount_uploader :file, ImageUploader
  
  validates :file, :presence => true
  
  belongs_to :user
  belongs_to :album
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :images
end

app/controllers/albums_controller.rb
# -*- encoding: utf-8 -*-
class AlbumsController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])
    @album.private = params[:private]

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: '电影集创建成功.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /images
  # GET /images.json
  def index
    @images = album.images.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = album.images.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = album.images.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = album.images.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = current_user.images.new(params[:image])  if params[:image][:album_id].nil? || params[:image][:album_id] == album.id.to_s

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = album.images.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = album.images.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end
  
  protected 
  def album
    @album ||= Album.find(params[:album_id])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  def index
    token = params[:token]
    album = Album.find_by_token(token)
	if album
      images = album.images
      gon.images = images.map { |image|  image.file.url('main') }
	else
	  gon.images = []
	end
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if album = Album.first
      gon.images = album.images.map { |image| image.file.url('main') }
	else
	  gon.images = []
	end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> 引起数据无法保存:</h2>
      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc, :rows => 10, :cols => 40 %>
  </div>
  <div class="field">
    <%= f.label :private %>
    <%= check_box_tag :private %>
    Tips: 如果设置隐私，那么别人将无法观看您的图片。
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h2>电影集列表</h2>
<%= link_to '创建新电影集', new_album_path %>
<table>
  <tr>
    <th>描述</th>
    <th>是否隐私</th>
    <th>唯一URL</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.desc %></td>
    <td><%= album.private %></td>
    <td><%= album.url %></td>
    <td><%= link_to '显示', album_images_path(album) %></td>
    <td><%= link_to '修改', edit_album_path(album) %></td>
    <td><%= link_to '删除', album, confirm: '肯定删除?', method: :delete %></td>
    <td><%= link_to "上传图片",  %></td>
  </tr>
<% end %>
</table>

<br />

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p>
  <b>Desc:</b>
  <%= @album.desc %>
</p>

<p>
  <b>Private:</b>
  <%= @album.private %>
</p>

<p>
  <b>Token:</b>
  <%= @album.token %>
</p>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/images/_form.html.erb
<%= form_for(@image,:url => album_image_path(@image.album ,@image), :html => {:multipart => true}) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> 不能保存数据:</h2>
      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file %><br />
    <%= f.file_field :file %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.number_field :order, :value => 1 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

app/views/images/index.html.erb
<p>
  <b>电影描述:</b>
  <%= @album.desc %>
</p>

<p>
  <b>隐私状态:</b>
  <%= @album.private %>
</p>

<p>
  <b>唯一地址:</b>
  <%= @album.url %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>
<p>
<h1>图片列表</h1>  <%= link_to '上传图片', new_album_image_path(@album) %>
</p>
<div id="images-pane">
<% @images.each do |image| %>
<div class="pane">
  <%=image_tag image.file.url("thumb"), :width => 150 %>
  <p>
    <%= link_to '修改', edit_album_image_path(@album, image) %>
    <%= link_to '删除', image, confirm: '确定删除?', method: :delete %>
  </p>
</div>
<% end %>
</div>
<div class="clearfix">

app/views/images/new.html.erb
<h1>上传图片</h1>

<%= render 'form' %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>File:</b>
  <%= @image.file %>
</p>

<p>
  <b>User:</b>
  <%= @image.user_id %>
</p>

<p>
  <b>Order:</b>
  <%= @image.order %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photosgame</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= include_gon %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <div id= "header">
    <div class="container">
      <div id="log">
        <h1>PhotosGame</h1>
      </div>
    <div class="navigate">
      <ul>
        
        <% if user_signed_in? %>
        <li><%=link_to "电影集", albums_url %></li>
        <% else %>
          <li><%=link_to "首页", root_url %></li>
          <li><%=link_to "关于PhotosGame", root_url %></li>
        <% end %>
      </ul>
    </div>
    <div class='info'>
     <% if user_signed_in? %>
     欢迎访问!
     <%=link_to "注销", destroy_user_session_path, :method => :delete %>
     <% else %>
     <%=link_to "注册", new_user_registration_path %>
     <%=link_to "登录", new_user_session_path %>
     <% end %>
    </div>
  </div>
  </div>
  <div class="container">
<%- if notice || alert -%>
  <div class="notice">
    <%= notice %>
    <%= alert %>
  </div>
<%- end -%>
  <div id="main">
<%= yield %>
</div>

  <div id="footer">
  版权所有@2012
</div>
</div>




</div>
</body>
</html>

app/views/photos/index.html.erb
<div id="main">
<h1>Photos</h1>
<p class="photo-info">
  width: 600px, height: 337px
<p>
<div id="photos">
  正在加载图片，请稍等... ...
</div>


</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "登录", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "注册", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "忘记密码?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "没有收到邮件?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "没有收到解锁通知?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "用#{provider.to_s.titleize}登录", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div id="main">
<h1>Photos</h1>
<p class="photo-info">
  width: 600px, height: 337px
<p>
<div id="photos">
  正在加载图片，请稍等... ...
</div>

<div class="block block_left">
  <h4>第一步：注册成为用户</h4>
    <p>
      您需要提供邮箱才能注册会员。只有成为会员，才可以使用本站提供的功能。
    </p>
</div>

<div class="block block_center">
  <h4>第一步：新建图片游戏</h4>
    <p>
      新建图片游戏后，系统会生成唯一的URL，并且有多种格式可供选择。
    </p>
</div>


<div class="block block_right">
  <h4>第一步：发布图片游戏</h4>
    <p>
      复制唯一地址，通过微博，博客等SNS工具发布您的最新作品。
    </p>
</div>


</div>